# Source: bucketrepo/templates/config-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: bucketrepo-config
  namespace: jx
  annotations:
    config/checksum: b1eb5b332c28e00b23a7c5486d015e0d78c687616523821242086ddccd823a24
    meta.helm.sh/release-name: 'bucketrepo'
type: Opaque
stringData:
  config.yaml: |
    http:
        addr: ":8080"
        username: "admin"
        password: ""
        chartPath: "charts"

    storage:
        bucket_url: ""

    cache:
        base_dir: "/tmp/bucketrepo"

    repositories:
        - url: "https://repo.maven.org/maven2"
        - url: "https://repo1.maven.org/maven2"
        - url: "https://services.gradle.org/distributions/"
        - url: "https://plugins.gradle.org/m2/"
        - url: "https://repo.jenkins-ci.org/public/"
        - url: "https://repo.jenkins-ci.org/releases/"
        - url: "https://jitpack.io/"
        - url: "https://registry.npmjs.org/"
        - url: "https://repo.spring.io/milestone/"
        - url: "https://repo.spring.io/release/"
        - url: "http://uk.maven.org/maven2/"
