# Source: docker-registry/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    app: docker-registry
    chart: docker-registry-1.9.6
    heritage: Helm
    release: docker-registry
  annotations:
    meta.helm.sh/release-name: 'docker-registry'
  namespace: jx
type: Opaque
data:
  haSharedSecret: "TTVXUHVPVWU0NGFIdVd4Ng=="
