# Source: bucketrepo/templates/secret.yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  annotations:
    jenkins.io/credentials-keybinding-password: BASIC_AUTH_PASS
    jenkins.io/credentials-keybinding-username: BASIC_AUTH_USER
    jenkins.io/foo: bar
    meta.helm.sh/release-name: 'bucketrepo'
  labels:
    jenkins.io/credentials-type: usernamePassword
    release: jenkins-x
  name: jenkins-x-bucketrepo
  namespace: jx
data:
  BASIC_AUTH_PASS: ""
  BASIC_AUTH_USER: "YWRtaW4="
